spring:
  datasource:
    username: postgres
    password: 37562012
    url: jdbc:postgresql:localhost:5432/movieDB

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect